### ISSUE TITLE
I need [items][header][items]. Possible?

### ISSUE THREAD

**Issue by Leonidos** [afollestad/sectioned-recyclerview#42]
Thank you for your library. I've been using it for a while with no issues but now I need to implement the following layout:

```
[item]
[item]
[section_header]
[item]
[item]
```

or

```
[item][item][item]
[item][item][item]
[section_header]
[item][item][item]
[item][item][item]
```

Is it possible? I checked sources and did't find a good way. For now I use negative layout margin top for RecyclerView to hide first header )

Thanks.

**Comment by afollestad** [comment]
Since this is a pretty niche thing, I don't think there should be an explicit option for it.

The best solution would be to return a different view type for the first item in `getItemViewType(int section, int relativePosition, int absolutePosition)`. From there, you can return an empty view in `onCreateViewHolder` and ignore it in `onBindViewHolder`. You'd then have an empty view that takes up no height in the first position.
